### ISSUE TITLE
istioctl create an route rule without namespace in the yaml.

### ISSUE THREAD

**Issue by fleeto** [istio/issues#110] opened 2017-10-27 12:18 UTC
**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version  0.2.9
kubectl version 1.7.6
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

No

**What happened**:

`Error: an empty namespace may not be set during creation`

**What you expected to happen:**

`routerule "reviews-test-v2" created`

**How to reproduce it:**

Following: https://istio.io/docs/tasks/security/basic-access-control.html#access-control-using-denials

`istioctl create -f samples/bookinfo/kube/route-rule-reviews-test-v2.yaml` 

But I can create this object with `kubectl apply -f`.

**Feature Request:**

N

**Describe the feature:**

**Comment by jmuk** [comment] 2017-10-27 18:08
Interesting, reproduced on my environment too. @ayj, do you have some ideas?

istioctl should scan the local kubernetes config file and extract the default namespace -- but at least `kubectl config view` does not show any namespace information on my environment.

**Comment by ayj** [comment] 2017-10-27 18:17
This should be partially fixed by https://github.com/istio/pilot/pull/1499. It also might be necessary to use the configured default namespace (see https://github.com/istio/pilot/pull/1373).

**Comment by jmuk** [comment] 2017-10-27 18:23
@ayj thanks for the pointer.

By the way, the patch looks like solving on CRD adapter for pilot, so same problem remains for mixer configs? I think this is not an ideal situation.

**Comment by jmuk** [comment] 2017-10-27 18:32
Filed https://github.com/istio/pilot/issues/1637, this is a separate item.

**Comment by craigbox** [comment] 2017-10-29 13:38
Fixed by https://github.com/istio/pilot/issues/1472?

**Comment by GregHanson** [comment] 2018-02-23 16:42
resolved by using istio version 0.5.1. or later

**Closed by GregHanson** 2018-02-23 16:42 UTC
