### ISSUE TITLE
Distributed tracing - spans not captured

### ISSUE THREAD

**Issue by saturnism** [istio/issues#72] opened 2017-09-25 19:29 UTC
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl 0.2.4
kubectl 1.7.5
```

**Is Istio Auth enabled or not ?** No

**What happened**:
Installed BookInfo. `productpage` is working fine.
Installed Zipkin, and visited `productpage` again.
Checked Zipkin UI to see the spans.  Rather than seeing multiple spans for each trace, I only see a single span for `details`

**What you expected to happen:**
See multiple spans for the multiple microservices that were called.

**How to reproduce it:**
See above.

**Comment by objectiser** [comment] 2017-09-26 15:09
This is most likely caused by a change in the way Envoy determines whether a span is client or server, based on whether the listener config is classified as Egress or Ingress. If you select the individual span in the zipkin UI, you should see many server received/sent annotations for each of the actual communications - as they all have been classified as server spans and due to the shared context approach within zipkin, they all share the same span id.

@rshriram In https://github.com/envoyproxy/envoy/pull/1565#pullrequestreview-59347693 you mentioned that an open bug regarding the operation name generated in Istio would be fixed before moving to the Envoy SHA - did that bug get fixed and included in 0.2.4?

I could only find one place where the operation name is assigned and it appears to only be set to Ingress: https://github.com/istio/pilot/blob/master/proxy/envoy/config.go#L327

**Comment by bismarck** [comment] 2017-09-26 15:57
@objectiser I saw a similar issue when testing with Jaeger.  However, when I refreshed the page for the trace, all the spans appeared.

**Closed** 2017-09-26 21:12 UTC
