### ISSUE TITLE
Panic happens while run "istioctl version"

### ISSUE THREAD

**Issue by flyxiao2000** [istio/issues#127] opened 2017-11-22 07:10 UTC
**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
ubuntu@master1:/etc$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2+coreos.0", GitCommit:"4c0769e81ab01f47eec6f34d7f1bb80873ae5c2b", GitTreeState:"clean", BuildDate:"2017-10-25T16:24:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2+coreos.0", GitCommit:"4c0769e81ab01f47eec6f34d7f1bb80873ae5c2b", GitTreeState:"clean", BuildDate:"2017-10-25T16:24:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

ubuntu@master1:/etc$ istioctl version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x11f21d9]

goroutine 1 [running]:
main.getDefaultNamespace(0xc4202f5b60, 0x19, 0x0, 0x0)
        cmd/istioctl/main.go:700 +0x99
main.glob..func4(0x1c32de0, 0x1c5ebe8, 0x0, 0x0)
        cmd/istioctl/main.go:86 +0x39
github.com/spf13/cobra.(*Command).execute(0x1c32de0, 0x1c5ebe8, 0x0, 0x0, 0x1c32de0, 0x1c5ebe8)
        external/com_github_spf13_cobra/command.go:637 +0x549
github.com/spf13/cobra.(*Command).ExecuteC(0x1c319a0, 0x41172d, 0xc4200002a8, 0x0)
        external/com_github_spf13_cobra/command.go:729 +0x339
github.com/spf13/cobra.(*Command).Execute(0x1c319a0, 0xc42004bf78, 0x434056)
        external/com_github_spf13_cobra/command.go:688 +0x2b
main.main()
        cmd/istioctl/main.go:531 +0xc0

```
**Describe the feature:**
My OS version: Ubuntu 16.04.3 LTS

**Comment by ayj** [comment] 2017-11-22 17:52
Duplicate of https://github.com/istio/istio/issues/1734 and https://github.com/istio/istio/issues/1734

**Closed by ayj** 2017-11-22 17:52 UTC
