### ISSUE TITLE
istio-pilot pod restart 60 times in nine days

### ISSUE THREAD

**Issue by johnzheng1975** [istio/issues#391] opened 2018-06-14 05:24 UTC
istio-pilot pod restart 60 times in nine days

ENVIRONMENT
- istio version: 0.8.0
- auth disabled
- k8s 1.9.5

![image](https://user-images.githubusercontent.com/17720035/41392839-9dfc4fc8-6fd5-11e8-92f8-85431b54fcd6.png)

[istio-pilot.log](https://github.com/istio/issues/files/2100901/istio-pilot.log)

**_kubectl describe pod istio-pilot-6c5c6b586c-z4th8 -n istio-system_**
Name:           istio-pilot-6c5c6b586c-z4th8
Namespace:      istio-system
Node:           ip-10-201-78-236.ec2.internal/10.201.78.236
Start Time:     Mon, 04 Jun 2018 15:26:57 +0000
Labels:         istio=pilot
                pod-template-hash=2717261427
Annotations:    cilium.io/identity=24268
                sidecar.istio.io/inject=false
Status:         Running
IP:             10.227.70.97
Controlled By:  ReplicaSet/istio-pilot-6c5c6b586c
Containers:
  discovery:
    Container ID:  docker://663d87e8bb28a55c678461cda24376913e254a23efa3c937ec08bef1990466e0
    Image:         docker.io/istio/pilot:0.8.0
    Image ID:      docker-pullable://istio/pilot@sha256:c9203d3d56aff27e12d43fb3882608fac49f56e6205cb12962cb8f04c1f29b44
    Ports:         8080/TCP, 15010/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      discovery
    State:          Running
      Started:      Tue, 12 Jun 2018 11:26:31 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 12 Jun 2018 11:25:16 +0000
      Finished:     Tue, 12 Jun 2018 11:26:16 +0000
    Ready:          True
    Restart Count:  59
    Readiness:      http-get http://:8080/v1/registration delay=30s timeout=5s period=30s #success=1 #failure=3
    Environment:
      POD_NAME:            istio-pilot-6c5c6b586c-z4th8 (v1:metadata.name)
      POD_NAMESPACE:       istio-system (v1:metadata.namespace)
      PILOT_THROTTLE:      500
      PILOT_CACHE_SQUASH:  5
    Mounts:
      /etc/certs from istio-certs (ro)
      /etc/istio/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-pilot-service-account-token-ngg68 (ro)
  istio-proxy:
    Container ID:  docker://68dea3baed4d618ab977ccaae6f8f978f98ef1e96210fe19bddc4849dcb28882
    Image:         docker.io/istio/proxyv2:0.8.0
    Image ID:      docker-pullable://istio/proxyv2@sha256:1930f0603321b1917b2249c576ecb4141aaceeaae5fcc0760b6a88dc88daea3e
    Ports:         15003/TCP, 15005/TCP, 15007/TCP, 15011/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      --serviceCluster
      istio-pilot
      --templateFile
      /etc/istio/proxy/envoy_pilot.yaml.tmpl
      --controlPlaneAuthPolicy
      NONE
    State:          Running
      Started:      Tue, 12 Jun 2018 00:44:31 +0000
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 04 Jun 2018 15:26:58 +0000
      Finished:     Tue, 12 Jun 2018 00:43:00 +0000
    Ready:          True
    Restart Count:  1
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAME:       istio-pilot-6c5c6b586c-z4th8 (v1:metadata.name)
      POD_NAMESPACE:  istio-system (v1:metadata.namespace)
      INSTANCE_IP:     (v1:status.podIP)
    Mounts:
      /etc/certs from istio-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-pilot-service-account-token-ngg68 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio
    Optional:  false
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-pilot-service-account
    Optional:    false
  istio-pilot-service-account-token-ngg68:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-pilot-service-account-token-ngg68
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:          <none>

**Comment by ymesika** [comment] 2018-06-14 07:47
Duplicate of https://github.com/istio/istio/issues/6276

**Closed by ymesika** 2018-06-14 07:47 UTC
