### ISSUE TITLE
Pod not accessible for the liveness probe, constant Envoy "unknown cluster" errors

### ISSUE THREAD

**Issue by markvincze** [istio/issues#147] opened 2018-01-02 15:35 UTC
**Is this a BUG or FEATURE REQUEST?:** Bug (I guess? Although of course it's possible that I have something misconfigured)

**Did you review existing epics or issues to identify if this already being worked on?**: Yes

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.4.0
kubectl version: client: v1.8.4, server: v1.8.4-gke.1
Installed on GKE
```

**Is Istio Auth enabled or not ?**
No

**What happened**: I'm deploying `istio-proxy` as a sidecar in a pod in which the main container has a liveness probe (which is a hard-coded `200 OK` response on a certain route).  
With the istio sidecar injected, the liveness probe fails. I can verify this by sshing into one of the k8s nodes and trying to `curl` the status endpoint with the IP of the pod, and I'm getting one of `curl: (56) Recv failure: Connection reset by peer` or `curl: (7) Failed to connect to 10.249.74.101 port 5000: Connection refused` or `curl: (52) Empty reply from server`.

In the meantime if I check the logs of the pod, I see that the `istio-proxy` container keeps constantly logging this error:

```
[2018-01-02 15:09:55.925][30][warning][upstream] external/envoy/source/server/lds_subscription.cc:68] lds: fetch failure: tcp proxy: unknown cluster 'out.orig-dst-cluster-tcp' in TCP route
```

![image](https://user-images.githubusercontent.com/1122274/34488994-ee57eb9c-efda-11e7-931d-329f38c810f5.png)

(I verified that my application in the actual container is working properly, if I open a bash session in either my container or in the `istio-proxy`, container, I can do `curl http://localhost:5000/status` successfully.)

Sometimes after a long time, ~20 minutes, the errors suddenly stop, and the livenes probe starts working.

**What you expected to happen:**
I was expecting the liveness probe to work always work.

**How to reproduce it:**
Deploy a pod with a liveness probe with the istio sidecar injected.

I'd really appreciate some pointers about how to start troubleshooting this issue.

**Comment by zinuga** [comment] 2018-01-12 12:23
@ayj can you take a look?

**Comment by ayj** [comment] 2018-01-13 01:07
I'm assuming this problem doesn't occur with liveliness probes disabled?

Can you describe your setup (e.g. mixer enabled, (no)auth) and how your k8s liveliness probes and service port/paths are configured? There are some combinations that are fully supported yet, e.g. https://github.com/istio/istio/blob/5976c82337a6216effb208b56f48920dae97210f/pilot/proxy/envoy/config.go#L1018.

**Comment by markvincze** [comment] 2018-01-16 09:31
Hi @ayj,

The setup of the istio installation is pretty standard, it's a Kubernetes cluster on GKE, and istio is installed with the official installer with default configuration to the `istio-system` namespace, without auth. @JorritSalverda, anything else special that comes to mind?

The sidecar is injected with `istioctl`.

Including the sidecar, the pod has 3 containers:
1. `myservice`: our actual API, listening on port 5000. Part of the config:
```
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /status
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    ports:
    - containerPort: 5000
      name: http-direct
      protocol: TCP
```
2. `myservice-nginx`: an nginx image used as a reverse proxy doing TLS offloading, listening on 80 and 443, and sending the traffic to port 5000.
3. `istio-proxy`

Any other info we should provide?

**Comment by ayj** [comment] 2018-01-17 21:32
The basic config above should work which I also verified in my test setup. The full k8s service and pod YAML would be good to verify port settings aren't conflicting. Outside of per-service/deployment configuration, this issue may be due to environmental factors (e.g total number of pods / services in the k8s cluster) that are contributing to overloading Pilot given default refresh interval. As you can experiment you could try the suggestions at https://github.com/istio/istio/issues/1485#issuecomment-357014162

**Comment by markvincze** [comment] 2018-01-18 11:53
@ayj Regarding increasing `rdsRefreshDelay` and `discoveryRefreshDelay`: I can do this by changing the args of the `istio-proxy` sidecar, right?

**Comment by markvincze** [comment] 2018-01-18 12:10
@ayj I tried changing these in the `istio-proxy` args, I increased `discoveryRefreshDelay` (the other one gives "unknown flag: --rdsRefreshDelay"), but the liveness probe is still failing the same way.

**Comment by ayj** [comment] 2018-01-18 19:04
`discoveryRefreshDelay` is the right flag. 

How are the full service and pod port definitions defined?

**Comment by emedina** [comment] 2018-01-19 14:12
Let me step in because I'm facing exactly the same issues with my installation in local VMWare VM Servers. And I still don't get how it works, as I've changed the `rdsRefreshDelay` and `discoveryRefreshDelay` to 30s and still it takes around 5 minutes to fetch everything from the `istio-pilot`.

Even when I leave them with 1s, still it takes around 5m to fetch all the routes.

My expectation would be that the `istio-proxy` fetches everything from the `istio-pilot` every Xs as per the configuration of `discoveryRefreshDelay`, but it's definitively not the case.

**Comment by ayj** [comment] 2018-01-19 17:05
A few things could be happening.

1) functional bug in liveliness/readiness probe configuration. Perhaps triggered by a conflict with existing service or container port in some unpredictable way. It could also be caused by  https://github.com/istio/istio/blob/c992106720b19a93ffbf3641913885fddd9c82e3/pilot/proxy/envoy/config.go#L1020. 

> // So, if a user wants to use kubernetes probes with Istio, she should ensure
// that the health check ports are distinct from the service ports.

@rshriram, do you rememeber if there were any other caveats w.r.t management ports that may lead to inconsistent / unreliable liveliness probes?

2) poor caching behavior in `istio-pilot` xDS delivery. `istio-pilot` maintains caches per LDS/CDS/RDS/SDS stream but eviction policy is fairly coarse grained and ends up flushing cache on any service/endpoint change in _any_ namespace AFAIK. Limiting testing to a dedicated cluster would help rule this out vs #1 above. Cache stats are available through the `/cache_stats` endpoint on `istio-pilot`. 

@nmittler, do you have any other tips/docs for debugging pilot performance and load issues?

3) insufficient resources for `istio-pilot`. The default install of `istio-pilot` has one replica without explicit resources constraints/limits. This is sufficient for bookinfo demo, but certainly needs more attention in larger clusters (see #2 about monitoring _all_ namespaces in the cluster). Increasing polling intervals (e.g. `rdsRefreshDelay`) helps alleviate some load at the expense of longer overall discovery times. Increasing replica count is also a consideration.

**Comment by emedina** [comment] 2018-01-19 17:05
After some more research, I realized that if I send a bunch of Pod creations at the same time, for some reason it takes the aforementioned 5 minutes to sync up. But if I create the Pods one by one or at least with a 1s delay between them, then everything works like a charm.

Seems like `istio-pilot` gets somehow overwhelmed when getting several requests at the same time, whereas if the requests are delayed by 1s, it can respond adequately. Bizarre...

BTW, left `rdsRefreshDelay` and `discoveryRefreshDelay` to 30s as it makes more sense.

**Comment by nmittler** [comment] 2018-01-19 19:31
@ldemailly are you aware of any perf testing that has been done for pilot to this point? It would be good to have something in place that we can track over time.

@emedina do you have a simple app handy that can replicate the problem?

**Comment by ldemailly** [comment] 2018-01-19 21:06
yes pilot is on the todo list though I've focused on the data path (envoy+mixer) so far.

I'm happy to show the tooling or discuss strategies and tactics for measuring and improving scalability with anyone that has time to volunteer

**Comment by emedina** [comment] 2018-01-20 14:54
Let me try to assemble something to share and get back to you, @nmittler

**Comment by ayj** [comment] 2018-03-22 17:59
The original issue was resolved by increasing Pilot replicas and increasing the refresh polling intervals. Furthermore, additional performance enhancements have been made to Pilot which improve scaling.

**Closed by ayj** 2018-03-22 17:59 UTC
Labels: kind/bug, kind/customer-issue
