### ISSUE TITLE
grafana nor servicegraph display data since 0.2.2

### ISSUE THREAD

**Issue by karmab** [istio/issues#59] opened 2017-09-15 19:53 UTC
**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**

this is an an openshift installed done with oc cluster up

```
istioctl version
Version: 0.2.2
GitRevision: 4d3e5b5dac116dfc840e21b9620b43e6c5f051a8
GitBranch: master
User: root@0926058fbc6f
GolangVersion: go1.8.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+695f48a16f", GitCommit:"d2e5420", GitTreeState:"clean", BuildDate:"2017-08-29T21:57:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
graphana and service graph dont display  any data though the mesh is properly installed ( routerules do work for instance) 

**What you expected to happen:**
data displayer for microservices

**How to reproduce it:**
deploy 0.2.2 release and run the bookapp sample app

**Feature Request:**
N

**Describe the feature:**

**Comment by karmab** [comment] 2017-09-15 19:55
deployment was done using the following script:

```
git clone https://github.com/istio/istio.git
cd istio
git checkout 9ac006e070b88dba19ad26048c1010675d77e321
oc login -u system:admin
oc new-project istio-system
oc adm policy add-scc-to-user anyuid -z default
oc adm policy add-scc-to-user privileged -z default
oc adm policy add-cluster-role-to-user cluster-admin -z default
oc adm policy add-cluster-role-to-user cluster-admin -z istio-pilot-service-account
oc adm policy add-cluster-role-to-user cluster-admin -z istio-ingress-service-account
oc adm policy add-cluster-role-to-user cluster-admin -z istio-egress-service-account
oc adm policy add-cluster-role-to-user cluster-admin -z istio-mixer-service-account
oc adm policy add-scc-to-user anyuid -z istio-ingress-service-account
oc adm policy add-scc-to-user privileged -z istio-ingress-service-account
oc adm policy add-scc-to-user anyuid -z istio-egress-service-account
oc adm policy add-scc-to-user privileged -z istio-egress-service-account
oc adm policy add-scc-to-user anyuid -z istio-pilot-service-account
oc adm policy add-scc-to-user privileged -z istio-pilot-service-account

oc create -f install/kubernetes/istio-rbac-beta.yaml
oc create -f install/kubernetes/istio.yaml
oc expose svc istio-ingress

sleep 20
oc apply -f install/kubernetes/addons/prometheus.yaml
oc apply -f install/kubernetes/addons/grafana.yaml
oc apply -f install/kubernetes/addons/servicegraph.yaml
oc expose svc servicegraph
oc expose svc grafana

curl -LO https://github.com/istio/istio/releases/download/0.2.2/istio-0.2.2-linux.tar.gz
tar zxvf istio-0.2.2-linux.tar.gz
sudo mv istio-0.2.2/bin/istioctl /usr/bin
sudo chmod u+x /usr/bin/istioctl

sleep 20
source istio.VERSION
oc apply -f <(istioctl kube-inject --hub $PILOT_HUB --tag $PILOT_TAG -f samples/apps/bookinfo/bookinfo.yaml -n myproject)
oc expose svc productpage
```

**Comment by debianmaster** [comment] 2017-09-17 02:53
+1 i dont see it either on k8s 1.7.5
in my case , applications are deployed in a different namespace (not istio-system)

**Comment by debianmaster** [comment] 2017-09-17 03:20
This is what i found  on prometheus target status
`Get http://istio-mixer.istio-system:42422/metrics: dial tcp 10.15.243.135:42422: getsockopt: connection refused`    may be issue with metrics on 42422  port.   other ports seem to work

**Comment by douglas-reid** [comment] 2017-09-18 16:09
Have you configured prometheus?  In 0.2.2, you have to supply configuration for prometheus via custom resources.

See: https://github.com/istio/istio/blob/master/samples/apps/bookinfo/rules/mixer-rule-standard-metrics.yaml for an example.

**Comment by karmab** [comment] 2017-09-18 16:33
thank you @douglas-reid for the information.
where can i get information on such changes within a new release? readthe docs for istio seems outdated :(

**Comment by douglas-reid** [comment] 2017-09-18 16:41
@karmab you are correct. the docs are currently outdated.

we are working on updating them right now. when we have a final release ready, the docs should match the new behavior.

**Comment by karmab** [comment] 2017-09-18 16:52
should i inject the prometheus resources in istio-system namespace rather?
the sample you provided uses istio-config-default namespace, which doesnt exist.

**Comment by douglas-reid** [comment] 2017-09-18 17:01
they can be injected in `istio-config-default`. they do not need to be in `istio-system`.

**Comment by karmab** [comment] 2017-09-18 17:05
sorry to insist, so should i create  namespace istio-config-default ?

**Comment by douglas-reid** [comment] 2017-09-18 17:38
sorry that I wasn't clear. creating a namespace for `istio-config-default` is fine, yes. it certainly should unblock you.

i think there is istio work ahead to choose the right default namespace and set it up appropriately.

**Comment by douglas-reid** [comment] 2017-09-19 03:32
@debianmaster strange. I was just able to do exactly what you describe, and send traffic through Mixer and see metrics in prometheus.

In the meantime, I'm working as I write this comment to add the resources to an appropriate place for deployment. I'll CC you on that PR.

**Comment by debianmaster** [comment] 2017-09-19 03:39
thanks @douglas-reid  i'll take a look when ready.   i'm using a gke cluster,  not sure if that matters.

**Comment by karmab** [comment] 2017-09-19 06:20
for what it's worth, despite creating the indicated rules in the proper namespace, i still dont see metrics ( nor the service relation in servicegraph), despite rules like routing ones getting properly taken into account.
i do have a dedicated istio-system namespace with the istio pods in it

**Comment by douglas-reid** [comment] 2017-09-19 15:51
All, please see: https://github.com/istio/istio/pull/866.

This solution was working for me in my testing.

**Comment by douglas-reid** [comment] 2017-09-20 15:14
OK. So, I've merged https://github.com/istio/istio/pull/866. This should provide configuration for Mixer with install.

To use those configs with grafana, you probably want to wait until https://github.com/istio/istio/pull/877 is merged as well, as there were updates to the grafana dashboard.

I'd love to have your feedback on usage.

**Comment by sdake** [comment] 2017-09-22 02:39
@douglas-reid I'll pull master and rebuild CentOS container today and get back to you.  I am also suffering from this problem.  I'll cherry-pick https://github.com/istio/istio/pull/877 as well.

**Comment by sdake** [comment] 2017-09-22 04:18
I can confirm mixer is now listening on port 42422:

<img width="1175" alt="screen shot 2017-09-21 at 9 12 28 pm" src="https://user-images.githubusercontent.com/755849/30729133-1012f994-9f12-11e7-9650-9eac34d0c2a9.png">

This was running CentOS 7.4 + CentOS 7.4 container images with all binaries rebuilt (mixer, pilot, and master of istio/istio).

**Comment by debianmaster** [comment] 2017-09-22 22:42
Good news:
works for me too on latest head.  (i.e prometheus target is up)  tested on mac/minikube 

Bad news:
Does not show any metrics in prometheus/grafna
@sdake  did grafana show metrics ?

**Comment by debianmaster** [comment] 2017-09-22 22:53
i can confirm it works for me.    (with grafana/prometheus) all

**Comment by ldemailly** [comment] 2017-09-23 02:50
thanks all !

**Closed by ldemailly** 2017-09-23 02:50 UTC
