### ISSUE TITLE
Deployment issue on OpenShift Platform

### ISSUE THREAD

**Issue by cmoulliard** [istio/issues#3] opened 2017-05-19 08:43 UTC
When we try to deploy istio on openshift, different issues are reported

Scenario followed

```
minishift start --memory 5000
oc new-project istio

oc apply -f install/kubernetes/istio-auth.yaml
oc apply -f install/kubernetes/addons/prometheus.yaml
oc apply -f install/kubernetes/addons/grafana.yaml
oc apply -f install/kubernetes/addons/servicegraph.yaml
oc apply -f install/kubernetes/addons/zipkin.yaml

oc expose svc/grafana
oc expose svc/servicegraph
oc expose svc/zipkin
```

Errors

1) Permission denied

The docker user which is used by grafana/prometheus container doesn't has the permission to change ownership or create a folder. 

```
oc logs grafana-851518138-z76l9
chown: changing ownership of '/data/grafana': Operation not permitted
chown: changing ownership of '/var/log/grafana': Operation not permitted

oc logs prometheus-3208567892-08nvd
time="2017-05-16T14:14:44Z" level=info msg="Starting prometheus (version=1.1.1, branch=release-1.0, revision=ab312a075f810e2ed124783c46d68674af071293)" source="main.go:73"
time="2017-05-16T14:14:44Z" level=info msg="Build context (go=go1.6.3, user=root@8ab14ddb4898, date=20160907-09:37:01)" source="main.go:74"
time="2017-05-16T14:14:44Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:221"
time="2017-05-16T14:14:44Z" level=error msg="Error opening memory series storage: mkdir data: permission denied" source="main.go:158"
```

2) Waiting to start as they are looking abut the secrets

The ingress and egress contains can't be started

```
oc logs istio-egress-1575870412-s1rs7
Error from server (BadRequest): container "proxy" in pod "istio-egress-1575870412-s1rs7" is waiting to start: ContainerCreating
oc logs istio-ingress-2905358108-j1fl9
Error from server (BadRequest): container "istio-ingress" in pod "istio-ingress-2905358108-j1fl9" is waiting to start: ContainerCreating

Events reported

Unable to mount volumes for pod "istio-egress-1575870412-s1rs7_istio(50e9ec5e-3a38-11e7-9bb6-f23b3a6d93cf)": timeout expired waiting for volumes to attach/mount for pod "istio"/"istio-egress-1575870412-s1rs7". list of unattached/unmounted volumes=[istio-certs]
MountVolume.SetUp failed for volume "kubernetes.io/secret/50c6a34e-3a38-11e7-9bb6-f23b3a6d93cf-istio-certs" (spec.Name: "istio-certs") pod "50c6a34e-3a38-11e7-9bb6-f23b3a6d93cf" (UID: "50c6a34e-3a38-11e7-9bb6-f23b3a6d93cf") with: secrets "istio.default" not found
```

3) istio manager

There is service account permission issue

```
I0516 14:19:15.164199       1 client.go:203] TPR "IstioConfig" is not ready (User "system:serviceaccount:istio:istio-manager-service-account" cannot list all istio.io.istioconfigs in the cluster). Waiting...
Error: 2 errors occurred:

* failed to register Third-Party Resources. User "system:serviceaccount:istio:istio-manager-service-account" cannot get extensions.thirdpartyresources at the cluster scope
* failed to register Third-Party Resources. Failed to create all TPRs
Usage:
  manager discovery [flags]

Flags:
      --discovery_cache   Enable caching discovery service responses (default true)
      --port int          Discovery service port (default 8080)
      --profile           Enable profiling via web interface host:port/debug/pprof (default true)

Global Flags:
      --kubeconfig string                Use a Kubernetes configuration file instead of in-cluster configuration
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --meshConfig string                ConfigMap name for Istio mesh configuration, config key should be "mesh" (default "istio")
  -n, --namespace string                 Select a namespace for the controller loop. If not set, uses ${POD_NAMESPACE} environment variable
      --resync duration                  Controller resync interval (default 1s)
  -v, --v Level                          log level for V logs (default 0)
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

E0516 14:19:16.165480       1 main.go:245] 2 errors occurred:

* failed to register Third-Party Resources. User "system:serviceaccount:istio:istio-manager-service-account" cannot get extensions.thirdpartyresources at the cluster scope
* failed to register Third-Party Resources. Failed to create all TPRs
```

**Comment by rshriram** [comment] 2017-05-19 13:26
Thank you for nicely categorizing the issues!
What version of kubernetes is this? And what release version did you test against? 
All three appear to be an RBAC issue. We did some RBAC related fixes in 0.1.3.

**Comment by cmoulliard** [comment] 2017-05-23 14:59
@rshriram The point 3) concerning the istio manager can't be resolved using a more recent version of RBAC or istio as the issue is due to the fact that OpenShift doesn't support Third Party resources - https://github.com/openshift/origin/issues/8622

**Comment by cmoulliard** [comment] 2017-05-23 15:00
> What version of kubernetes is this?

```
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
```

**Comment by smarterclayton** [comment] 2017-05-26 12:59
The istio default secret - how is that added?

The 1 above is because the images try to chown their owner directories (running as root) and openshift denies running as root by default.  You'd need to enable SCC (Kube PodSecurityPolicy) to allow you to run as root, which the openshift docs cover.  

The istio.default secret is probably because the controller failed to start.

**Comment by debianmaster** [comment] 2017-06-13 05:31
i was able to run  istio  0.1.5 and 0.1.6   both on openshift 1.5 https://www.youtube.com/watch?v=RzOdpk-QFCk   https://github.com/debianmaster/openshift-examples/tree/master/istio

**Comment by cmoulliard** [comment] 2017-06-13 10:34
Great workaround @debianmaster. I will have a look

**Comment by debianmaster** [comment] 2017-06-13 19:28
and openshift does has TPR supports from 1.5

**Comment by bjartek** [comment] 2017-07-10 09:20
I can confirm that this works. However in order to run it with SELinux enabled please see issue https://github.com/istio/issues/issues/34

**Comment by ldemailly** [comment] 2017-09-21 04:11
closing this one then

**Closed by ldemailly** 2017-09-21 04:11 UTC
Labels: Openshift, platform compatibility
